### ISSUE TITLE
bug: TypeError: _NamedCellStyle.__init__() got an unexpected keyword argument 'biltinId'

### ISSUE THREAD

**Issue by jgroc-de** [theorchard/openpyxl#14]
Hi,

when trying to open an excel (.xlsx) file, i got this error:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    load_workbook(filename='old.xlsx')
  File "~/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 317, in load_workbook
    reader.read()
  File "~/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 281, in read
    apply_stylesheet(self.archive, self.wb)
  File "~/.local/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py", line 198, in apply_stylesheet
    stylesheet = Stylesheet.from_tree(node)
  File "~/.local/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py", line 103, in from_tree
    return super(Stylesheet, cls).from_tree(node)
  File "~/.local/lib/python3.10/site-packages/openpyxl/descriptors/serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "~/.local/lib/python3.10/site-packages/openpyxl/descriptors/serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "~/.local/lib/python3.10/site-packages/openpyxl/descriptors/serialisable.py", line 103, in from_tree
    return cls(**attrib)
TypeError: _NamedCellStyle.__init__() got an unexpected keyword argument 'biltinId'

if i open this file with calc or microsoft excel and re-save it, this error disappears.
i tried it with another python lib to open excel files and it works so i guess it is something for openpyxl.

Badfully, i am not sure i can give you an exemple file for testing purpose...
Ask me if ever the stacktrace is not enough.

thx for the lib anyway.

**Comment by jlaine** [comment]
I got bitten by the same problem here, and examining the contents of the file, it looks as though `builtinId` was misspelled as `biltinId` in the `xl/styles.xml` document. Was the document you are trying to parse by any chance created by a company named `Erival Ingénierie`?

**Comment by jgroc-de** [comment]
nop, but it seems they use the same tools i was facing: windev…

**Comment by jlaine** [comment]
Do you have a way to get in touch with the `windev` developers to get them to fix this typo?

**Comment by spertch9a** [comment]
Hi everyone,
@jlaine  @jgroc-de 
I also have that case with Windev23, this workaround is valid for all those cases, the problem is with the styling of the file 

I encountered a similar issue with corrupted Excel files while using `openpyxl` and found a workaround using Excel's COM API through Python's `pywin32` library. The workaround involves opening the Excel file using Excel itself and saving it again, which appears to resolve the corruption issue.

Here is the Python function I used:

```python
import win32com.client
import os

def save_as_excel(input_file, output_file):
    try:
        # Start Excel application
        excel = win32com.client.Dispatch("Excel.Application")
        excel.Visible = False  # Hide Excel window (set to True if you want to see Excel working)

        # Open the workbook
        workbook = excel.Workbooks.Open(input_file)

        # Save As the file in the same format (xlsx)
        workbook.SaveAs(output_file)

        # Close the workbook
        workbook.Close(SaveChanges=True)
        excel.Quit()

        print(f"✅ File saved as: {output_file}")

    except Exception as e:
        print(f"❌ Error during Save As: {e}")
        return False

    return True

# Example usage
input_file = r"C:\path\to\your\inputfile.xlsx"
output_file = r"C:\path\to\your\outputfile.xlsx"

save_as_excel(input_file, output_file)
```

### How it works:
- **Excel COM Automation**: The script uses the Excel application through `win32com.client` to open the corrupt Excel file and then save it as a new file. This action essentially "repairs" the file by forcing Excel to rewrite it, which resolves the issues with file corruption that some users (including myself) have encountered when using `openpyxl` to process files.
- **Output**: The new file (`output_file`) is saved in the same format (`.xlsx`), and it can be safely loaded and processed using `openpyxl`.

### Example Usage:
- Replace the `input_file` and `output_file` paths with your specific file paths. This script will process the file and save a repaired version, which can then be read using `openpyxl` without issues.

Let me know if this solution works for you, or if you need further assistance!
