### ISSUE TITLE
Error in OpenPyXL when parsing active xlsx header filters

### ISSUE THREAD

**Issue by True-Demon** [theorchard/openpyxl#2]
The following stacktrace occurs when parsing a table with openpyxl while header filters are active. The presence of header filters don't affect anything, but if I have a list of values and I save an xlsx file while I am filtering for a value, it causes the following:

```
Traceback (most recent call last):
# My code starts here
  File "/usr/local/bin/my_script", line 405, in <module>
    main()
  File "/usr/local/bin/my_script", line 381, in main
    assets = load_assets_file(arguments.assets_file, arguments.asset_columns)
  File "/usr/local/bin/my_script", line 115, in load_assets_file # load_assets_file is my xlsx sheet
    workbook = openpyxl.load_workbook(file_path)

# OpenPyxl takes over here. In this case, I am just trying to parse the entire tree from the table (workbook)
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/reader/excel.py", line 265, in load_workbook
    table = Table.from_tree(xml)

# Getting individual element values from the workbook...
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/serialisable.py", line 79, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/serialisable.py", line 79, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/serialisable.py", line 79, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/serialisable.py", line 92, in from_tree
    return cls(**attrib)

# This is where the error is actually encountered, because I accidentally left a filter active
# In this case, it was just a simple list of values, and I filtered one of the other columns
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/worksheet/filters.py", line 168, in __init__
    self.operator = operator    
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/base.py", line 145, in __set__
    super(NoneSet, self).__set__(instance, value)
  File "/usr/local/lib/python3.6/dist-packages/openpyxl/descriptors/base.py", line 130, in __set__
    raise ValueError(self.__doc__)
ValueError: Value must be one of {'lessThan', 'notEqual', 'equal', 'greaterThanOrEqual', 'lessThanOrEqual', 'greaterThan'}
```

I won't presume to understand your guys' workflow, but if I had to suggest a change, I might include a new exception type so that this error would be easier to debug. (took me an hour to figure out what I did wrong)

This would allow me as the user of openpyxl to discover why my script broke much faster, and point me directly to the filters issue. In addition, it would be awesome if an optional condition could be set to ignore filters and parse the entire tree regardless of the presence of filters.

Thanks for your guys' hard work on this library. It's saved me a lot of headache many times over. Cheers.

**Comment by True-Demon** [comment]
Sorry, I didn't realize this was being maintained on bitbucket. I'll close and reopen the issue there.
